# Generated by Django 5.2.6 on 2025-09-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("P", "درصدی"), ("F", "مبلغ ثابت")],
                        max_length=1,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مقدار"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر از تاریخ"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر تا تاریخ"
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="حداقل مبلغ خرید",
                    ),
                ),
                (
                    "target_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="store.category",
                        verbose_name="دسته بندی های هدف",
                    ),
                ),
                (
                    "target_customers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="store.customer",
                        verbose_name="مشتریان هدف",
                    ),
                ),
                (
                    "target_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="store.product",
                        verbose_name="محصولات هدف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیف ها",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.discount",
                verbose_name="تخفیف اعمال شده",
            ),
        ),
    ]
