# Generated by Django 5.2.6 on 2025-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_discount_order_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="تصویر محصول"
            ),
        ),
    ]
