# Generated by Django 5.2.6 on 2025-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="فروشگاه من", max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="لوگوی فروشگاه",
                        null=True,
                        upload_to="logos/",
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=255)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                (
                    "primary_color",
                    models.CharField(
                        default="#6366f1", help_text="رنگ اصلی (فرمت هگز)", max_length=7
                    ),
                ),
            ],
            options={
                "verbose_name": "پیکربندی سایت",
                "verbose_name_plural": "پیکربندی سایت",
            },
        ),
    ]
